schema_version = "1.0.0"

# Basic Add-on Info
id = "kitsune_source_tools"
name = "Kitsune Source Tools"
version = "0.6.1"
tagline = "A forked of BlenderSourceTools, an Importer and exporter for Valve Software's Source Engine Models"
maintainer = "Tom Edwards (BlenderSourceTools) & Toppi (KitsuneSourceTools)"
type = "add-on"
website = "http://steamcommunity.com/groups/BlenderSourceTools"

# Blender Compatibility
blender_version_min = "4.5.0"

# Licensing
license = [
    "SPDX:GPL-2.0-or-later"
]

# Permissions
permissions = ["files"]

# Optional Metadata
tags = [
    "Import-Export",
    "Source Engine",
]